export { SlashCommandConfigurator } from './base.js';
export { ConfiguratorRegistry, registry } from './registry.js';
export { AntigravityConfigurator } from './antigravity.js';
export { ClaudeConfigurator } from './claude.js';
export { CodexConfigurator } from './codex.js';
export { GithubCopilotConfigurator } from './github-copilot.js';
export { OpenCodeConfigurator } from './opencode.js';
export { KiloCodeConfigurator } from './kilocode.js';
export { ForgeConfigurator } from './forge.js';
export { DroidConfigurator } from './droid.js';
