#!/usr/bin/env bun

import matter from "gray-matter"
import path from "path"

const dir = path.resolve(import.meta.dirname, "..")
const skillsDir = path.join(dir, "src", "anvil", "skills")
const outputPath = path.join(dir, "src", "anvil", "skills.ts")

function jsString(input: string) {
  return JSON.stringify(input).replace(/[^\x20-\x7E]/g, (char) =>
    `\\u${char.charCodeAt(0).toString(16).padStart(4, "0")}`,
  )
}

const files = (await Array.fromAsync(new Bun.Glob("*/SKILL.md").scan({ cwd: skillsDir, absolute: true }))).sort()

const skills = await Promise.all(
  files.map(async (file) => {
    const parsed = matter(await Bun.file(file).text())
    const name = parsed.data.name
    const description = parsed.data.description
    const folder = path.basename(path.dirname(file))

    if (typeof name !== "string" || name.length === 0) {
      throw new Error(`${file}: missing required frontmatter field "name"`)
    }
    if (typeof description !== "string" || description.length === 0) {
      throw new Error(`${file}: missing required frontmatter field "description"`)
    }
    if (name !== folder) {
      throw new Error(`${file}: skill name "${name}" must match folder "${folder}"`)
    }

    return {
      name,
      description,
      location: `anvil://skills/${name}/SKILL.md`,
      content: parsed.content.trim(),
    }
  }),
)

const entries = skills.map((skill) =>
  [
    "  {",
    `    name: ${jsString(skill.name)},`,
    `    description: ${jsString(skill.description)},`,
    `    location: ${jsString(skill.location)},`,
    `    content: ${jsString(skill.content)},`,
    "  },",
  ].join("\n"),
)

await Bun.write(
  outputPath,
  [
    "// This file is generated by script/generate-anvil-skills.ts.",
    "// Do not edit it directly. Add or update src/anvil/skills/*/SKILL.md instead.",
    "",
    "export const ANVIL_SKILLS = [",
    ...entries,
    "] as const",
    "",
  ].join("\n"),
)

console.log(`Generated ${path.relative(dir, outputPath)} with ${skills.length} Anvil skill(s)`)
